version: '3'

services:
    mqtt2statsd:
        build:
          context: mqtt2statsd/
        restart: always
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/etc/timezone:/etc/timezone:ro"
          - "./mqtt2statsd/application:/opt/application"
        command: python3 ./main.py
